name       : python-cepa
version    : 1.8.3
release    : 2
source     :
    - https://pypi.io/packages/source/c/cepa/cepa-1.8.3.tar.gz : 1dc6f0b324d37a2ed2ca274648ece8fd2c96a1d2f440f58c0ca17afd4b5ede7a
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Stem is a Python controller library that allows applications to interact with Tor (https://www.torproject.org/).
description: |
    Stem is a Python controller library for Tor. With it you can use Tor's control protocol to script against the Tor process, or build things such as Nyx.
builddeps  :
    - python-cryptography
    - pyflakes
    - pycodestyle
    - tor
rundeps    :
    - python-cryptography
setup      : |
    %apply_patches
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test run_tests.py --unit --target RUN_ALL
#    %python3_test run_tests.py --integ --target RUN_ALL
